"""modify user model

Revision ID: d9b31a76b3fa
Revises: 2c2b845f4e90
Create Date: 2023-07-12 11:10:43.647453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b31a76b3fa'
down_revision = '2c2b845f4e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('preferences', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'token')
    op.drop_column('user', 'preferences')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
