"""change user_id to id and token to user_id

Revision ID: db6a1cc0d8a1
Revises: 62cc1a1b361a
Create Date: 2023-07-19 07:57:27.992569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6a1cc0d8a1'
down_revision = '62cc1a1b361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # remove the existing primary key constraint so that we can rename it
    op.drop_constraint('tennis_user_pkey', 'tennis_user', type_='primary')
    # rename the primary key column
    op.alter_column('tennis_user', 'user_id', nullable=False,
                    new_column_name='tennis_user_id')
    # re-create the primary key constraint with the new column name
    op.create_primary_key('tennis_user_pkey',
                          'tennis_user', ['tennis_user_id'])

    op.alter_column('tennis_user', 'token',
                    new_column_name='auth_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # remove the existing primary key constraint so that we can rename it
    op.drop_constraint('tennis_user_pkey', 'tennis_user', type_='primary')
    # rename the primary key column
    op.alter_column('tennis_user', 'tennis_user_id', nullable=False,
                    new_column_name='user_id')
    # re-create the primary key constraint with the new column name
    op.create_primary_key('tennis_user_pkey',
                          'tennis_user', ['user_id'])

    op.alter_column('tennis_user', 'auth_user_id',
                    new_column_name='token')
    # ### end Alembic commands ###
